defmodule Socho.Studies.Registry do
  @moduledoc "Reads the jsPsych plugin registry generated by assets/setup_jspsych.mjs."

  def all do
    path = Path.join(:code.priv_dir(:socho), "jspsych_registry.json")
    path |> File.read!() |> Jason.decode!()
  end

  def get(plugin_name), do: all()[plugin_name]

  def plugin_names, do: all() |> Map.keys() |> Enum.sort()
end
