defmodule Socho.Studies.Registry do
  @moduledoc "Reads the jsPsych plugin registry generated by assets/setup_jspsych.mjs."

  def all do
    npm = load_json("jspsych_registry.json")
    custom = load_json("custom_plugins_registry.json")
    Map.merge(npm, custom)
  end

  def get(plugin_name), do: all()[plugin_name]

  def plugin_names, do: all() |> Map.keys() |> Enum.sort()

  def custom_plugin_names do
    load_json("custom_plugins_registry.json") |> Map.keys()
  end

  defp load_json(filename) do
    path = Path.join(:code.priv_dir(:socho), filename)
    if File.exists?(path), do: path |> File.read!() |> Jason.decode!(), else: %{}
  end
end
